using Grpc.Core;
using Grpc.Net.Client;
using Nexusvpn.Api;
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace NexusVPN
{
    public class CoreBridge
    {
        private readonly PlatformBridge.PlatformBridgeClient _client;
        private readonly string _tokenPath;
        private string? _token;
        public event Action<string>? OnStateChanged;

        public CoreBridge()
        {
            var channel = GrpcChannel.ForAddress("http://localhost:50051"); 
            _client = new PlatformBridge.PlatformBridgeClient(channel);
            
            // Read Localhost IPC Token generated by the NT Service securely
            _tokenPath = Path.Combine(
                Environment.GetEnvironmentVariable("LOCALAPPDATA") ?? Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "NexusVPN",
                "grpc.token");

            RefreshTokenIfAvailable();
        }

        private Metadata GetHeaders()
        {
            RefreshTokenIfAvailable();
            var headers = new Metadata();
            if (!string.IsNullOrEmpty(_token)) {
                headers.Add("authorization", $"Bearer {_token}");
            }
            return headers;
        }

        private void RefreshTokenIfAvailable()
        {
            if (!File.Exists(_tokenPath))
            {
                return;
            }

            var token = File.ReadAllText(_tokenPath).Trim();
            if (!string.IsNullOrWhiteSpace(token))
            {
                _token = token;
            }
        }

        public async Task ConnectAsync(string profileId)
        {
            try {
                await _client.ConnectAsync(new ConnectRequest { ProfileId = profileId }, headers: GetHeaders());
            } catch (RpcException e) {
                HandleRpcException(e);
                throw CreateBridgeException(e);
            }
        }

        public async Task DisconnectAsync()
        {
            try {
                await _client.DisconnectAsync(new DisconnectRequest(), headers: GetHeaders());
            } catch (RpcException e) {
                HandleRpcException(e);
                throw CreateBridgeException(e);
            }
        }

        public async Task<string> ImportConfigAsync(string payload)
        {
            try
            {
                var response = await _client.ImportConfigAsync(new ImportRequest { Payload = payload }, headers: GetHeaders());
                return response.ProfileId;
            }
            catch (RpcException e)
            {
                HandleRpcException(e);
                throw CreateBridgeException(e);
            }
        }

        public async Task ListenToStateAsync(CancellationToken token)
        {
            try {
                var call = _client.GetState(new StateRequest(), headers: GetHeaders(), cancellationToken: token);
                await foreach (var response in call.ResponseStream.ReadAllAsync(token))
                {
                    OnStateChanged?.Invoke(response.State);
                }
            } catch (RpcException e) {
                if (e.StatusCode == StatusCode.Cancelled && token.IsCancellationRequested)
                {
                    return;
                }

                HandleRpcException(e);
            }
        }

        private Exception CreateBridgeException(RpcException e)
        {
            return new InvalidOperationException(e.Status.Detail, e);
        }

        private void HandleRpcException(RpcException e) {
            // Fix Stage 13 mapping logic: differentiating AUTH and UNAVAILABLE
            if (e.StatusCode == StatusCode.Unauthenticated) {
                RefreshTokenIfAvailable();
                OnStateChanged?.Invoke("ERROR: UNAUTHENTICATED TOKEN");
            } else if (e.StatusCode == StatusCode.Unavailable) {
                OnStateChanged?.Invoke("ERROR: DAEMON UNAVAILABLE");
            } else if (e.StatusCode == StatusCode.DeadlineExceeded) {
                OnStateChanged?.Invoke("ERROR: IPC TIMEOUT");
            } else {
                OnStateChanged?.Invoke("ERROR: " + e.Status.Detail);
            }
        }
    }
}
