using Grpc.Core;
using Grpc.Net.Client;
using Nexusvpn.Api;
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace NexusVPN
{
    public class CoreBridge
    {
        private PlatformBridge.PlatformBridgeClient _client;
        private string? _token;
        public event Action<string>? OnStateChanged;

        public CoreBridge()
        {
            var channel = GrpcChannel.ForAddress("http://localhost:50051"); 
            _client = new PlatformBridge.PlatformBridgeClient(channel);
            
            // Read Localhost IPC Token generated by the NT Service securely
            string tokenPath = Path.Combine(
                Environment.GetEnvironmentVariable("LOCALAPPDATA") ?? Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "NexusVPN",
                "grpc.token");
            if (File.Exists(tokenPath)) {
                _token = File.ReadAllText(tokenPath).Trim();
            }
        }

        private Metadata GetHeaders() {
            var headers = new Metadata();
            if (!string.IsNullOrEmpty(_token)) {
                headers.Add("authorization", $"Bearer {_token}");
            }
            return headers;
        }

        public async Task ConnectAsync(string profileId)
        {
            try {
                await _client.ConnectAsync(new ConnectRequest { ProfileId = profileId }, headers: GetHeaders());
            } catch (RpcException e) {
                HandleRpcException(e);
            }
        }

        public async Task DisconnectAsync()
        {
            try {
                await _client.DisconnectAsync(new DisconnectRequest(), headers: GetHeaders());
            } catch (RpcException e) {
                HandleRpcException(e);
            }
        }

        public async Task ListenToStateAsync(CancellationToken token)
        {
            try {
                var call = _client.GetState(new StateRequest(), headers: GetHeaders(), cancellationToken: token);
                await foreach (var response in call.ResponseStream.ReadAllAsync(token))
                {
                    OnStateChanged?.Invoke(response.State);
                }
            } catch (RpcException e) {
                HandleRpcException(e);
            }
        }

        private void HandleRpcException(RpcException e) {
            // Fix Stage 13 mapping logic: differentiating AUTH and UNAVAILABLE
            if (e.StatusCode == StatusCode.Unauthenticated) {
                OnStateChanged?.Invoke("ERROR: UNAUTHENTICATED TOKEN");
            } else if (e.StatusCode == StatusCode.Unavailable) {
                OnStateChanged?.Invoke("ERROR: DAEMON UNAVAILABLE");
            } else if (e.StatusCode == StatusCode.DeadlineExceeded) {
                OnStateChanged?.Invoke("ERROR: IPC TIMEOUT");
            } else {
                OnStateChanged?.Invoke("ERROR: " + e.Status.Detail);
            }
        }
    }
}
